#!/usr/bin/env bash

# Resolve the full absolute path of the script
SCRIPT_PATH="$(readlink -f "$0")"

(
  cd "$(dirname "$SCRIPT_PATH")/.." && uv run python -OO -m "$(basename "$(dirname "$SCRIPT_PATH")")" "$@"
)
